### PR TITLE
Pass fragment matcher to graphql()

### PR DESCRIPTION
**Pull request by const86**
Needed in cases when selection set contains inline fragments.
Without fragment matcher graphql() runs attempts to resolve
all fields and fails.

### CODE REVIEW

**Comment by const86** [comment]
#257

**Comment by const86** [comment]
See #260 for Travis failure.

**Comment by fbartho** [comment]
@const86 -- this PR is ready for master-merge/rebase! -- Also, I think this same fix needs to be made in apollo-link-rest too, if you're up for it!

**Comment by fbartho** [comment]
@const86 Do you think this is necessary for [apollo-link-rest](https://github.com/apollographql/apollo-link-rest)?

**Pull request merged**
