### PR TITLE
Allow to provide resolvers via function

### PR DESCRIPTION
**Pull request by kamilkisiela**
So we can lazy load resolvers

### CODE REVIEW

**Comment by kamilkisiela** [comment]
It's a Bird...It's a Plane...It's @jbaxleyiii !

**Comment by fbartho** [comment]
What if you want dynamic imports for resolvers? -- should this instead be an Async Function?

**Comment by kamilkisiela** [comment]
Sure, maybe, but I don't need that. Maybe someone that needs that would create another PR later on.

**Comment by evans** [comment]
@kamilkisiela Thank you so much!

**Pull request merged**
