### PR TITLE
Fix Error when Bundling with Rollup

### PR DESCRIPTION
**Pull request by bennypowers**
When bundling apollo-link-state with rollup, this error is thrown:
```
[!] Error: 'graphql' is not exported by node_modules/graphql-anywhere/lib/async.js
```

This PR should fix that error

See https://github.com/apollographql/apollo-client/issues/3276

- [ ] feature
- [x] blocking
- [ ] docs

### CODE REVIEW

**Comment by fbartho** [comment]
@bennypowers I was just struggling with this same issue in apollo-link-rest (I didn't find the solution you did)! -- If you're feeling up to submitting a PR over there, I'd appreciate it!

Also, if you merge/rebase this with master, the Travis build should be able to go green!

**Comment by zeusorion** [comment]
@fbartho I'm having the same issues with rollup and this change seems to have fixed it, what's the progress of the PR? thx!

**Comment by fbartho** [comment]
@bennypowers -- This PR doesn't give me Push rights so I can merge in master, and fix an issue I detected:

```diff
commit 9f5b2285134e4c6d7b6e9873e8763ac23f3d5de5
Author: Frederic Barthelemy
Date:   Thu Jun 7 14:55:27 2018 -0700

    Required tweak to run jest-tests correctly

diff --git a/packages/apollo-link-state/src/index.ts b/packages/apollo-link-state/src/index.ts
index 9408c8d..751402d 100644
--- a/packages/apollo-link-state/src/index.ts
+++ b/packages/apollo-link-state/src/index.ts
@@ -8,7 +8,7 @@ import {
 import { ApolloCache } from 'apollo-cache';

 import { hasDirectives, getMainDefinition } from 'apollo-utilities';
-import Async from 'graphql-anywhere/lib/async';
+import * as Async from 'graphql-anywhere/lib/async';
 const { graphql } = Async;
 import { FragmentMatcher } from 'graphql-anywhere';
```

@zeusorion This PR appears to break when running in `yarn test` inside the `packages/apollo-link-state/` directory, so I'd love to help this get done but I'm a little stuck. -- I'm also at a conference today. Anyhow, happy to help somebody get this over the finish line.

**Comment by fbartho** [comment]
@bennypowers looks like the build failed again :(

**Comment by bennypowers** [comment]
I'm happy to grant access to my fork to anyone with the time and inclination to fiddle with this

**Comment by bennypowers** [comment]
Thank you :D

**Comment by nripendra** [comment]
When will this fix be released to npm?

**Pull request merged**
